/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMethod = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductPlan = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
  'referral_bonus' : IDL.Null,
  'purchase' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'paymentMethod' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'notes' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'user' : IDL.Principal,
  'referralEarnings' : IDL.Nat,
  'referredBy' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPaymentMethod' : IDL.Func([PaymentMethod], [], []),
  'approveTransaction' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDepositRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getAllPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'getAllProductPlans' : IDL.Func([], [IDL.Vec(ProductPlan)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatformStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalUsers' : IDL.Nat, 'totalTransactions' : IDL.Nat })],
      ['query'],
    ),
  'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processPurchase' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [UserProfile], []),
  'rejectTransaction' : IDL.Func([IDL.Nat], [], []),
  'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMethod = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductPlan = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
    'referral_bonus' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'paymentMethod' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'notes' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'user' : IDL.Principal,
    'referralEarnings' : IDL.Nat,
    'referredBy' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPaymentMethod' : IDL.Func([PaymentMethod], [], []),
    'approveTransaction' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDepositRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getAllPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getAllProductPlans' : IDL.Func([], [IDL.Vec(ProductPlan)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatformStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalUsers' : IDL.Nat, 'totalTransactions' : IDL.Nat })],
        ['query'],
      ),
    'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processPurchase' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [UserProfile], []),
    'rejectTransaction' : IDL.Func([IDL.Nat], [], []),
    'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };