/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PaymentMethod { 'name' : string, 'description' : string }
export interface ProductPlan {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : TransactionStatus,
  'paymentMethod' : string,
  'createdAt' : Time,
  'user' : Principal,
  'notes' : string,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null } |
  { 'referral_bonus' : null } |
  { 'purchase' : null };
export interface UserProfile {
  'referralCode' : string,
  'username' : string,
  'balance' : bigint,
  'user' : Principal,
  'referralEarnings' : bigint,
  'referredBy' : [] | [Principal],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPaymentMethod' : ActorMethod<[PaymentMethod], undefined>,
  'approveTransaction' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDepositRequest' : ActorMethod<[bigint, string, string], bigint>,
  'getAllPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getAllProductPlans' : ActorMethod<[], Array<ProductPlan>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatformStats' : ActorMethod<
    [],
    { 'totalUsers' : bigint, 'totalTransactions' : bigint }
  >,
  'getUserBalance' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processPurchase' : ActorMethod<[bigint, [] | [string]], bigint>,
  'registerUser' : ActorMethod<[string, [] | [string]], UserProfile>,
  'rejectTransaction' : ActorMethod<[bigint], undefined>,
  'removePaymentMethod' : ActorMethod<[string], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint, string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserBalance' : ActorMethod<[Principal, bigint], undefined>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];